In [67]:
import pandas as pd

In [68]:
stats = pd.read_csv("player_mvp_stats.csv", index_col=0)

In [69]:
stats

,Player,Pos,Age,Tm,G_x,GS,MP,FG,FGA,FG%,...,Share,G_y,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,SF,31.0,PHO,82.0,52.0,32.8,3.8,7.5,0.504,...,NaN,NaN,Phoenix Suns,59.0,23.0,0.720,—,110.6,106.8,3.86
1,Aaron Swinson,SF,24.0,PHO,9.0,0.0,5.7,1.1,2.0,0.556,...,NaN,NaN,Phoenix Suns,59.0,23.0,0.720,—,110.6,106.8,3.86
2,Antonio Lang,SF,22.0,PHO,12.0,0.0,4.4,0.3,0.8,0.400,...,NaN,NaN,Phoenix Suns,59.0,23.0,0.720,—,110.6,106.8,3.86
3,Charles Barkley,PF,31.0,PHO,68.0,66.0,35.0,8.1,16.8,0.486,...,0.091,68.0,Phoenix Suns,59.0,23.0,0.720,—,110.6,106.8,3.86
4,Dan Majerle,SF,29.0,PHO,82.0,46.0,37.7,5.3,12.6,0.425,...,NaN,NaN,Phoenix Suns,59.0,23.0,0.720,—,110.6,106.8,3.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14239,Spencer Hawes,PF,28.0,MIL,54.0,1.0,14.8,2.5,5.1,0.484,...,NaN,NaN,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45
14240,Steve Novak,PF,33.0,MIL,8.0,0.0,2.8,0.3,0.9,0.286,...,NaN,NaN,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45
14241,Terrence Jones,PF,25.0,MIL,54.0,12.0,23.5,4.3,9.1,0.470,...,NaN,NaN,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45
14242,Thon Maker,C,19.0,MIL,57.0,34.0,9.9,1.5,3.2,0.459,...,NaN,NaN,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45
14243,Tony Snell,SG,25.0,MIL,80.0,80.0,29.2,3.1,6.8,0.455,...,NaN,NaN,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45

In [6]:
del stats["Unnamed: 0"]

In [7]:
stats

,Player,Pos,Age,Tm,G_x,GS,MP,FG,FGA,FG%,...,Share,G_y,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,SF,31.0,PHO,82.0,52.0,32.8,3.8,7.5,0.504,...,NaN,NaN,Phoenix Suns,59.0,23.0,0.720,—,110.6,106.8,3.86
1,Aaron Swinson,SF,24.0,PHO,9.0,0.0,5.7,1.1,2.0,0.556,...,NaN,NaN,Phoenix Suns,59.0,23.0,0.720,—,110.6,106.8,3.86
2,Antonio Lang,SF,22.0,PHO,12.0,0.0,4.4,0.3,0.8,0.400,...,NaN,NaN,Phoenix Suns,59.0,23.0,0.720,—,110.6,106.8,3.86
3,Charles Barkley,PF,31.0,PHO,68.0,66.0,35.0,8.1,16.8,0.486,...,0.091,68.0,Phoenix Suns,59.0,23.0,0.720,—,110.6,106.8,3.86
4,Dan Majerle,SF,29.0,PHO,82.0,46.0,37.7,5.3,12.6,0.425,...,NaN,NaN,Phoenix Suns,59.0,23.0,0.720,—,110.6,106.8,3.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14239,Spencer Hawes,PF,28.0,MIL,54.0,1.0,14.8,2.5,5.1,0.484,...,NaN,NaN,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45
14240,Steve Novak,PF,33.0,MIL,8.0,0.0,2.8,0.3,0.9,0.286,...,NaN,NaN,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45
14241,Terrence Jones,PF,25.0,MIL,54.0,12.0,23.5,4.3,9.1,0.470,...,NaN,NaN,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45
14242,Thon Maker,C,19.0,MIL,57.0,34.0,9.9,1.5,3.2,0.459,...,NaN,NaN,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45
14243,Tony Snell,SG,25.0,MIL,80.0,80.0,29.2,3.1,6.8,0.455,...,NaN,NaN,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45

In [70]:
pd.isnull(stats).sum()

Player         0
Pos            0
Age            0
Tm             0
G_x            0
GS             0
MP             0
FG             0
FGA            0
FG%           58
3P             0
3PA            0
3P%         1886
2P             0
2PA            0
2P%          103
eFG%          58
FT             0
FTA            0
FT%          549
ORB            0
DRB            0
TRB            0
AST            0
STL            0
BLK            0
TOV            0
PF             0
PTS            0
Year           0
Pts Won    13805
Pts Max    13805
Share      13805
G_y        13805
Team           0
W            572
L            572
W/L%         572
GB           572
PS/G         572
PA/G         572
SRS          572
dtype: int64

In [12]:
stats[pd.isnull(stats["FT%"])][["Player", "FTA"]]

                Player  FTA
22          John Coker  0.0
37        Jason Sasser  0.0
48     Adrian Caldwell  0.0
64        Bruno Šundov  0.0
103     Jamal Robinson  0.0
...                ...  ...
14064      George King  0.0
14150     Trevor Keels  0.0
14158      Luke Zeller  0.0
14206      Malcolm Lee  0.0
14240      Steve Novak  0.0

[549 rows x 2 columns]

In [71]:

stats = stats.fillna(0)

In [72]:
stats

,Player,Pos,Age,Tm,G_x,GS,MP,FG,FGA,FG%,...,Share,G_y,Team,W,L,W/L%,GB,PS/G,PA/G,SRS
0,A.C. Green,SF,31.0,PHO,82.0,52.0,32.8,3.8,7.5,0.504,...,0.000,0.0,Phoenix Suns,59.0,23.0,0.720,—,110.6,106.8,3.86
1,Aaron Swinson,SF,24.0,PHO,9.0,0.0,5.7,1.1,2.0,0.556,...,0.000,0.0,Phoenix Suns,59.0,23.0,0.720,—,110.6,106.8,3.86
2,Antonio Lang,SF,22.0,PHO,12.0,0.0,4.4,0.3,0.8,0.400,...,0.000,0.0,Phoenix Suns,59.0,23.0,0.720,—,110.6,106.8,3.86
3,Charles Barkley,PF,31.0,PHO,68.0,66.0,35.0,8.1,16.8,0.486,...,0.091,68.0,Phoenix Suns,59.0,23.0,0.720,—,110.6,106.8,3.86
4,Dan Majerle,SF,29.0,PHO,82.0,46.0,37.7,5.3,12.6,0.425,...,0.000,0.0,Phoenix Suns,59.0,23.0,0.720,—,110.6,106.8,3.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14239,Spencer Hawes,PF,28.0,MIL,54.0,1.0,14.8,2.5,5.1,0.484,...,0.000,0.0,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45
14240,Steve Novak,PF,33.0,MIL,8.0,0.0,2.8,0.3,0.9,0.286,...,0.000,0.0,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45
14241,Terrence Jones,PF,25.0,MIL,54.0,12.0,23.5,4.3,9.1,0.470,...,0.000,0.0,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45
14242,Thon Maker,C,19.0,MIL,57.0,34.0,9.9,1.5,3.2,0.459,...,0.000,0.0,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45
14243,Tony Snell,SG,25.0,MIL,80.0,80.0,29.2,3.1,6.8,0.455,...,0.000,0.0,Milwaukee Bucks,42.0,40.0,0.512,9.0,103.6,103.8,-0.45

In [74]:
stats.columns

Index(['Player', 'Pos', 'Age', 'Tm', 'G_x', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'Pts Won', 'Pts Max', 'Share', 'G_y', 'Team', 'W', 'L', 'W/L%', 'GB',
       'PS/G', 'PA/G', 'SRS'],
      dtype='object')

In [82]:
predictors = ["Age", "G_y", "GS", "MP", "FG", "FGA", 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'W', 'L', 'W/L%', 'PS/G', 'PA/G', 'SRS']

In [83]:
train = stats[~(stats["Year"] == 2024)]
test = stats[stats["Year"] == 2024]

In [84]:
test = stats[stats["Year"] == 2024]

In [85]:
from sklearn.linear_model import Ridge

reg = Ridge(alpha=.1)

In [86]:
reg.fit(train[predictors],train["Share"])

Ridge(alpha=0.1)

In [87]:
predictions = reg.predict(test[predictors])
predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)

In [62]:
predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)

In [63]:
predictions

       predictions
143    -304.878872
144    -304.667877
145    -305.582277
146    -305.028137
147    -304.884920
...            ...
12917  -304.910908
12918  -305.034678
12919  -305.218822
12920  -305.398361
12921  -305.052824

[572 rows x 1 columns]

In [88]:
combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)

In [90]:
combination

                  Player  Share  predictions
143           A.J. Green    0.0     0.044465
144    Andre Jackson Jr.    0.0     0.033211
145         Bobby Portis    0.0     0.050616
146          Brook Lopez    0.0     0.040572
147     Chris Livingston    0.0     0.038286
...                  ...    ...          ...
12917          Max Strus    0.0     0.035455
12918         Pete Nance    0.0     0.042011
12919        Sam Merrill    0.0     0.044509
12920   Tristan Thompson    0.0     0.037265
12921          Ty Jerome    0.0     0.029722

[572 rows x 3 columns]

In [91]:
combination.sort_values("Share", ascending=False).head(20)

                        Player  Share  predictions
711               Nikola Jokić  0.935     0.271826
1349   Shai Gilgeous-Alexander  0.646     0.259601
260                Luka Dončić  0.572     0.269930
150      Giannis Antetokounmpo  0.194     0.294971
3795             Jalen Brunson  0.143     0.231156
2875              Jayson Tatum  0.087     0.236857
8197           Anthony Edwards  0.018     0.230628
4182          Domantas Sabonis  0.003     0.250454
11530             Kevin Durant  0.001     0.235667
9778           Cade Cunningham  0.000     0.056202
9777             Buddy Boeheim  0.000     0.044325
9779             Chimezie Metu  0.000     0.044079
9597          Keita Bates-Diop  0.000     0.036618
9776            Ausar Thompson  0.000     0.036828
9603           Trendon Watford  0.000     0.043803
9602              Noah Clowney  0.000     0.039803
9601               Nic Claxton  0.000     0.056925
9600             Mikal Bridges  0.000     0.044946
9599          Lonnie Walker IV  0.000     0.041862
9598              Keon Johnson  0.000     0.039124

In [92]:
from sklearn.metrics import mean_squared_error

mean_squared_error(combination["Share"], combination["predictions"])

0.0034098098861257762

In [93]:
combination["Share"].value_counts()

0.000    563
0.194      1
0.572      1
0.935      1
0.646      1
0.087      1
0.143      1
0.003      1
0.018      1
0.001      1
Name: Share, dtype: int64

In [94]:
actual = combination.sort_values("Share", ascending=False)
predicted = combination.sort_values("predictions", ascending=False)
actual["Rk"] = list(range(1,actual.shape[0]+1))
predicted["Predicted_Rk"] = list(range(1,predicted.shape[0]+1))

In [95]:
actual.merge(predicted, on="Player").head(5)

,Player,Share_x,predictions_x,Rk,Share_y,predictions_y,Predicted_Rk
0,Nikola Jokić,0.935,0.271826,1,0.935,0.271826,2
1,Shai Gilgeous-Alexander,0.646,0.259601,2,0.646,0.259601,4
2,Luka Dončić,0.572,0.269930,3,0.572,0.269930,3
3,Giannis Antetokounmpo,0.194,0.294971,4,0.194,0.294971,1
4,Jalen Brunson,0.143,0.231156,5,0.143,0.231156,8

In [96]:
def find_ap(combination):
    actual = combination.sort_values("Share", ascending=False).head(5)
    predicted = combination.sort_values("predictions", ascending=False)
    ps = []
    found = 0
    seen = 1
    for index,row in predicted.iterrows():
        if row["Player"] in actual["Player"].values:
            found += 1
            ps.append(found / seen)
        seen += 1

    return sum(ps) / len(ps)

In [97]:
ap = find_ap(combination)

In [98]:
ap

0.925

In [99]:
years = list(range(1995,2024))

In [100]:
aps = []
all_predictions = []
for year in years[5:]:
    train = stats[stats["Year"] < year]
    test = stats[stats["Year"] == year]
    reg.fit(train[predictors],train["Share"])
    predictions = reg.predict(test[predictors])
    predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)
    combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
    all_predictions.append(combination)
    aps.append(find_ap(combination))

In [101]:

sum(aps) / len(aps)

0.7668841806341807

In [102]:
def add_ranks(predictions):
    predictions = predictions.sort_values("predictions", ascending=False)
    predictions["Predicted_Rk"] = list(range(1,predictions.shape[0]+1))
    predictions = predictions.sort_values("Share", ascending=False)
    predictions["Rk"] = list(range(1,predictions.shape[0]+1))
    predictions["Diff"] = (predictions["Rk"] - predictions["Predicted_Rk"])
    return predictions

In [103]:
add_ranks(all_predictions[1])

                 Player  Share  predictions  Predicted_Rk   Rk  Diff
1093      Allen Iverson  0.904     0.174239             7    1    -6
9186         Tim Duncan  0.569     0.201506             2    2     0
12461  Shaquille O'Neal  0.466     0.287882             1    3     2
9735       Chris Webber  0.420     0.198191             3    4     1
8773      Kevin Garnett  0.122     0.178504             6    5    -1
...                 ...    ...          ...           ...  ...   ...
9178         Ira Newble  0.000     0.003871           155  437   282
12748     Scott Padgett  0.000     0.003960           154  438   284
10457       Dana Barros  0.000     0.004052           153  439   286
104         Ricky Davis  0.000     0.004135           152  440   288
14020        Jason Hart  0.000    -0.061792           441  441     0

[441 rows x 6 columns]

In [104]:
def backtest(stats, model, years, predictors):
    aps = []
    all_predictions = []
    for year in years:
        train = stats[stats["Year"] < year]
        test = stats[stats["Year"] == year]
        model.fit(train[predictors],train["Share"])
        predictions = model.predict(test[predictors])
        predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)
        combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
        combination = add_ranks(combination)
        all_predictions.append(combination)
        aps.append(find_ap(combination))
    return sum(aps) / len(aps), aps, pd.concat(all_predictions)

In [105]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[5:], predictors)

In [106]:
mean_ap

0.7668841806341807

In [124]:
reg.coef_

array([ 2.95763809e-04,  2.51366103e-02, -1.26349867e-03, -1.85324966e-02,
       -1.09777277e-02,  1.08834336e-02, -4.97921646e-03,  3.78512763e-05,
       -8.22639769e-03, -4.38414911e-04,  2.03655832e-02, -4.75335964e-02,
       -6.72655615e-04,  2.00453520e-03, -1.93337541e-02,  1.58909339e-02,
        5.09042761e-04,  1.82488923e-02,  5.05730266e-02, -6.14783949e-02,
       -3.36811490e-02,  6.44489249e-03,  4.15078428e-02, -2.32087632e-03,
       -2.55283642e-04,  3.09371715e-02,  2.43686890e-04,  1.96547510e-03,
        3.76039752e-03,  1.38333866e-04, -2.23137333e-03, -2.14361796e-03,
        2.31967716e-02,  3.91615448e-02, -4.72021075e-03, -4.02975164e-02,
       -5.94492609e-03])

In [107]:
all_predictions[all_predictions["Rk"] < 5].sort_values("Diff").head(10)

                Player  Share  predictions  Predicted_Rk  Rk  Diff
1450        Jason Kidd  0.712     0.100115            18   2   -16
5450        Steve Nash  0.839     0.114210            15   1   -14
13000      Joakim Noah  0.258     0.150990            15   4   -11
5483        Steve Nash  0.785     0.153983            12   2   -10
5531   Carmelo Anthony  0.393     0.149658            13   3   -10
8822   Peja Stojaković  0.228     0.122154            14   4   -10
5468        Steve Nash  0.739     0.134917            10   1    -9
12424     Derrick Rose  0.977     0.164324            10   1    -9
7062       Kobe Bryant  0.873     0.169146             9   1    -8
8930       Joel Embiid  0.580     0.167423             9   2    -7

In [108]:
pd.concat([pd.Series(reg.coef_), pd.Series(predictors)], axis=1).sort_values(0, ascending=False)

           0     1
13  0.033000  eFG%
18  0.028261   DRB
28  0.022374  W/L%
17  0.022130   ORB
15  0.009286   FTA
25  0.009245   PTS
10  0.008594    2P
5   0.003974   FGA
21  0.003340   STL
22  0.002998   BLK
20  0.002750   AST
16  0.002470   FT%
1   0.001987   G_y
27  0.000069     L
0   0.000056   Age
2  -0.000045    GS
26 -0.000062     W
31 -0.000186   SRS
30 -0.000198  PA/G
29 -0.000262  PS/G
24 -0.000476    PF
3  -0.001726    MP
12 -0.001856   2P%
23 -0.002691   TOV
9  -0.004934   3P%
4  -0.005890    FG
8  -0.006817   3PA
7  -0.007378    3P
11 -0.012883   2PA
14 -0.014382    FT
19 -0.024986   TRB
6  -0.066613   FG%

In [125]:
stat_ratios = stats[["PTS", "AST", "STL", "BLK", "3P", "Year", ]].groupby("Year").apply(lambda x: x/x.mean())

/var/folders/xt/5mwj_mdd04b95r90st_cvh480000gn/T/ipykernel_24250/3398229967.py:1: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  stat_ratios = stats[["PTS", "AST", "STL", "BLK", "3P", "Year", ]].groupby("Year").apply(lambda x: x/x.mean())

In [126]:
stats.head()

,Player,Pos,Age,Tm,G_x,GS,MP,FG,FGA,FG%,...,PS/G,PA/G,SRS,PTS_R,AST_R,STL_R,BLK_R,3P_R,NPos,NTm
0,A.C. Green,SF,31.0,PHO,82.0,52.0,32.8,3.8,7.5,0.504,...,110.6,106.8,3.86,1.319103,0.758048,0.991605,0.931570,1.107162,8,28
1,Aaron Swinson,SF,24.0,PHO,9.0,0.0,5.7,1.1,2.0,0.556,...,110.6,106.8,3.86,0.317998,0.151610,0.141658,0.000000,0.000000,8,28
2,Antonio Lang,SF,22.0,PHO,12.0,0.0,4.4,0.3,0.8,0.400,...,110.6,106.8,3.86,0.105999,0.050537,0.000000,0.465785,0.000000,8,28
3,Charles Barkley,PF,31.0,PHO,68.0,66.0,35.0,8.1,16.8,0.486,...,110.6,106.8,3.86,2.708873,2.071999,2.266527,1.630247,2.435757,2,28
4,Dan Majerle,SF,29.0,PHO,82.0,46.0,37.7,5.3,12.6,0.425,...,110.6,106.8,3.86,1.837322,2.071999,1.699895,1.164462,5.314379,8,28

In [110]:
stats[["PTS_R", "AST_R", "STL_R", "BLK_R", "3P_R"]] = stat_ratios[["PTS", "AST", "STL", "BLK", "3P"]]

In [111]:
predictors += ["PTS_R", "AST_R", "STL_R", "BLK_R", "3P_R"]

In [112]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[5:], predictors)

In [113]:
mean_ap

0.7834797201708966

In [114]:
stats["NPos"] = stats["Pos"].astype("category").cat.codes
stats["NTm"] = stats["Tm"].astype("category").cat.codes

In [115]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=50, random_state=1, min_samples_split=5)

mean_ap, aps, all_predictions = backtest(stats, rf, years[28:], predictors + ["NPos", "NTm"])

In [116]:

mean_ap

0.9028571428571428

In [117]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[28:], predictors)

In [118]:
mean_ap

0.7544444444444445

In [119]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

In [120]:
def backtest(stats, model, years, predictors):
    aps = []
    all_predictions = []
    for year in years:
        train = stats[stats["Year"] < year].copy()
        test = stats[stats["Year"] == year].copy()
        sc.fit(train[predictors])
        train[predictors] = sc.transform(train[predictors])
        test[predictors] = sc.transform(test[predictors])
        model.fit(train[predictors],train["Share"])
        predictions = model.predict(test[predictors])
        predictions = pd.DataFrame(predictions, columns=["predictions"], index=test.index)
        combination = pd.concat([test[["Player", "Share"]], predictions], axis=1)
        combination = add_ranks(combination)
        all_predictions.append(combination)
        aps.append(find_ap(combination))
    return sum(aps) / len(aps), aps, pd.concat(all_predictions)

In [121]:
mean_ap, aps, all_predictions = backtest(stats, reg, years[28:], predictors)

In [122]:
mean_ap

0.7544444444444445

In [123]:
sc.transform(stats[predictors])

array([[ 1.0020667 , -0.17905191,  0.93968409, ..., -0.01221212,
        -0.05943951,  0.08925358],
       [-0.62401877, -0.17905191, -0.87462142, ..., -1.24868923,
        -0.868616  , -0.83288165],
       [-1.08861461, -0.17905191, -0.87462142, ..., -1.45476875,
        -0.46402776, -0.83288165],
       ...,
       [-0.39172084, -0.17905191, -0.45593553, ...,  0.17376803,
         1.34389646, -0.39914955],
       [-1.78550838, -0.17905191,  0.31165526, ..., -0.98947252,
         0.23764023, -0.29071653],
       [-0.39172084, -0.17905191,  1.91661783, ...,  0.17376803,
        -0.42611351,  1.1189128 ]])